#%RAML 1.0
title: Metadata API
version: v1
baseUri: http://metadata.org/api
mediaType:
  - application/json
  - application/xml
protocols:
  - HTTP
  - HTTPS
description: An API specification for accessing statistical metadata
types:
  ClassificationListType:
    type: !include schemas/metadata-api.xsd#URICodeLabelListType
  ClassificationDetailsType:
      type: !include schemas/metadata-api.xsd#ClassificationDetailsType
  ClassificationSchemeListType:
      type: !include schemas/metadata-api.xsd#URICodeLabelListType
  ClassificationSchemeDetailsType:
    type: !include schemas/metadata-api.xsd#ClassificationSchemeDetailsType
  LevelListType:
      type: !include schemas/metadata-api.xsd#URICodeLabelListType
  ItemListType:
      type: !include schemas/metadata-api.xsd#URICodeLabelListType

/classifications:
  get:
    displayName: Get classification list
    description: Gets the list of all available classifications
    responses:
      200:
        body:
          application/xml:
            type: ClassificationListType

/classification/{codeClassification}:
  get:
    displayName: Gets classification details
    description: Get details on a classification with code {codeClassification}
    responses:
      200:
        body:
          application/xml:
            type: ClassificationDetailsType

/classification/{codeClassification}/schemes:
  get:
    displayName: Get schemes of a classification
    description: Gets the list of schemes for the classification with code {codeClassification}
    responses:
      200:
        body:
          application/xml:
            type: ClassificationSchemeListType
            
/correspondences/{codeClassification}/{targetCodeClassification}:
  get:
    displayName: Get correspondences between a classification and a target classification
    description: Gets the list of correspondences between a classification with code {codeClassification} and a target classification with code {targetCodeClassification}
    responses:
      200:
        body:
          application/xml:
            type: ClassificationSchemeListType            

/schemes:
  get:
    displayName: Get classifications schemes
    description: Gets the list of all available classification schemes (classification major versions)
    responses:
      200:
        body:
          application/xml:
            type: ClassificationSchemeListType

/scheme/{codeScheme}:
  get:
    displayName: Get classification scheme details
    description: Gets the details on a classification scheme with code {codeScheme}
    responses:
      200:
        description: Successful GET request
        body:
          application/xml:
            type: ClassificationSchemeDetailsType

/scheme/{codeScheme}/levels:
  get:
    displayName: Get classification scheme levels
    description: Gets the levels of a classification scheme with code {codeScheme}
    responses:
      200:
        description: Successful GET request
        body:
          application/xml:
            type: LevelListType

/scheme/{codeScheme}/items:
  get:
    displayName: Get classification scheme items
    description: Gets the items of a classification scheme with code {codeScheme}
    responses:
      200:
        description: Successful GET request
        body:
          application/xml:
            type: ItemListType

/scheme/{codeScheme}/level/{codeLevel}/items:
  get:
    displayName: Get classification scheme items for a given level
    description: Gets the items of a classification scheme with code {codeScheme} belonging to the with code {codeLevel}
    responses:
      200:
        description: Successful GET request
        body:
          application/xml:
            type: ItemListType
