name: MetaData API
services:
  metadata-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - fr.insee.rmes.api.sparqlEndpoint=http://graphdb:7200
    links:
      - graphdb
  graphdb:
    image: ontotext/graphdb:10.6.4
    restart: always
    ports:
      - "7200:7200"
    environment:
      GDB_JAVA_OPTS: "-Xmx1g -Xms512M"